// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// g_FDR
NumericVector g_FDR(NumericMatrix fdr);
RcppExport SEXP PanDM_g_FDR(SEXP fdrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fdr(fdrSEXP);
    rcpp_result_gen = Rcpp::wrap(g_FDR(fdr));
    return rcpp_result_gen;
END_RCPP
}
