# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g_FDR <- function(fdr) {
    .Call('PanDM_g_FDR', PACKAGE = 'PanDM', fdr)
}

